site_name: Goldbro's Second Mind
site_url: https://wiki.goldbro.top
site_description: The ideas in my mind explode like stars
theme:
  name: material
  language: zh
  palette:
    primary: indigo
    
    media: "(prefers-color-scheme)"
    toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    
    media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: 
    text: LXGW WenKai TC
    code: JetBrains Mono
  features:
    - navigation.instant  #即时加载功能
    - navigation.tabs     #上方导航栏
    - navigation.tabs.sticky  #上方导航栏始终显示
    - toc.follow          #侧边栏始终跟随保持活动锚点可见
    - toc.integrate       #目录导航集成始终可见 
    - navigation.top      #回到顶部按钮
    - search.suggest      #设置搜索建议
    - search.highlight    #设置搜索高亮
  icon:
    logo: material/brain  #更换站点的主图表和侧栏图表
    repo: fontawesome/brands/git-alt
  favicon:  https://img.goldbro.top/goldbro_ico.jpg    #更换站点favico

plugins:
  - rss:
      enabled: false
  
  - search
  
  - git-revision-date-localized:
      type: timeago #时间类型
      custom_format: "%d. %B %Y"  # 时间格式
      timezone: Asia/Shanghai #时区
      locale: zh #首选语言
      fallback_to_build_date: false #许回退到git 不可用时mkdocs build执行的时间
      enable_creation_date: true #是否启用创建时间
      exclude:  #排除的页面
          - index.md
      enabled: true #是否启用
      strict: true
  
  - git-committers:
      repository: GoldBro233/wiki
      branch: main

copyright: >-
  Copyright &copy; 2024 Goldbro233
  Please Follow CC BY-NC-SA 4.0


extra:
  consent:
    title: Cookie consent
    description: >- 
      我们使用 cookies 来识别您重复的访问和偏好，并衡量我们文档的有效性以及用户是否找到他们正在搜索的内容。通过您的同意，您正在帮助我们改进文档。
    actions:
      - accept
      - reject
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/GoldBro233
    - icon: material/email-fast
      link: mailto:admin@goldbro.top

repo_url: https://github.com/GoldBro233/wiki
repo_name: GoldBro233/wiki

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js